version: "3"

services:

  popara-neo4j:
    container_name: popara-neo4j
    image: neo4j:latest
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/conf:/conf
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_logs_debug_level=INFO
    restart: unless-stopped

  turlitava:
    container_name: turlitava
    image: slaviq/turlitava:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - popara-neo4j

volumes:
  popara-neo4j: