version: "3"
services:
  neo4j:
    container_name: popara-neo4j
    image: neo4j:latest
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/conf:/conf
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_logs_debug_level=INFO
#      - NEO4J_dbms_default__database=neo4j
#      - NEO4J_AUTH=neo4j/neo4j
#      - NEO4J_apoc_export_file_enabled=true
#      - NEO4J_apoc_import_file_enabled=true
#      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
#      - NEO4J_apoc_uuid_enabled=true
#      - NEO4J_dbms_default__listen__address=0.0.0.0
#      - NEO4J_dbms_allow__upgrade=true
#    networks: ["popara-neo4j"]
    restart: unless-stopped
#networks: { popara-neo4j: {} }
# use docker volume to persist data outside of a container.
volumes:
  popara-neo4j: